QP/C++: qk_sched.cpp File Reference
qk_sched.cpp File Reference
QK_sched_() implementation.
#include "qk_pkg.h"
Functions
void QK_sched_ (uint8_t p)
The QK scheduler.
Detailed Description
QK_sched_() implementation.
Definition in file qk_sched.cpp.
Function Documentation
void QK_sched_ (uint8_t p)
The QK scheduler.
Note:
The QK scheduler must be always called with the interrupts locked and unlocks interrupts internally.
See also:
QK_schedPrio_()
Definition at line 51 of file qk_sched.cpp.
References QF::active_, QS::aoObj_, QPSet64::findMax(), QF::gc(), QK_currPrio_, QK_readySet_, QK_TLS, QS_BEGIN_NOCRIT_, QS_END_NOCRIT_, QS_QK_SCHEDULE, and QS_U8_.
Referenced by QK::mutexUnlock().